commit_message: "\UF09F8C90üåê Crowdin Translation Update [skip "
append_commit_message: 
pull_request_title: "\UF09F8C90üåê Crowdin Translation Upd"
pull_request_labels:
  - crowdin
files:
  - source: /ClickMeister/Resource/Localization/source.xaml
    translation: /ClickMeister/Resource/Localization/Language/%locale%.%file_extension%
